= 🚀 Shell Velocity
:toc:

A portable https://en.wikipedia.org/wiki/Notational_Velocity[notational velocity] for your shell written in POSIX shell.

video::https://user-images.githubusercontent.com/96259932/223130698-f870c17c-f307-40c0-b48f-050173bf3d18.mp4[options=autoplay]

== Features

* Removes cognitive load by combining the note creation and note searching
* Customizable (use your preferred fuzzy finder or file picker; see link:docs/tested-pickers.adoc[tested pickers])
* Uses whatever editor you want (even link:docs/visual-studio-code.adoc[Visual Studio Code])
* Portable (runs on every POSIX compatible OS, see link:docs/tested-oses.adoc[Tested OSes])
* Minimal (only a POSIX shell and the picker of your choice)
* Nonintrusive (use markdown by default, but works also with your preferred markup languages such as: https://orgmode.org/[org], https://github.com/nvim-neorg/neorg[neorg], rest, https://asciidoc.org/[adoc], etc)

== Dependencies

* POSIX compliant shell
* POSIX utils
* https://github.com/junegunn/fzf[`fzf`] or your favorite picker (e.g. fzy, rofi, dmenu, etc)

== Installation

=== Arch Linux (AUR)

[,bash]
----
yay -S shell-velocity-git
----

=== Manual

IMPORTANT: Make sure that `~/.local/bin` is in your `PATH`.

[,bash]
----
mkdir -p ~/.local/bin
curl https://raw.githubusercontent.com/saccarosium/shell-velocity/main/shv -o ~/.local/bin/shv
chmod +x ~/.local/bin/shv
----

== Usage

NOTE: Every subcommand that uses your `$SHV_PICKER` is capable of creating a new file directly from the picker if not match is found.

=== Available commands

[,bash]
----
shv search <default> # search through all your notes
shv [select | sel] # select a note from your $SHV_PATH
shv [bookmarks | bms | b] <number> # select one of your bookmarks
shv diary # select a note from diary folder
shv [yesterday | ye | y] <label> # edit yesterday diary note
shv [today | t] <label> # edit todays diary note
shv [tomorrow | tom | tm] <label> # edit tomorrow diary note
shv [history | hist | h] # select notes from note editing history
----

==== no args

Launches `$SHV_DEFAULT_CMD` (by default `search`).

.launch shv witout arguments
[,bash]
----
shv
----

==== search

`grep` all the files with your `$SHV_EXTS` in your `$SHV_PATH`. If no match is found, or you use the keybinding to create a note (if your `$SHV_PICKER` support keybindings), a new note will be created.

==== select

Select one, or more, of your files by filename (a more traditional fuzzy search through files).

==== bookmarks

Edit a file you edit often by simply using the number is located in `$SHV_BMS`

[,bash]
----
shv bookmarks 1
----

==== diary

Searches in your `$SHV_DIARY_PATH` for notes, and uses your picker to select what daily file to choose.

==== yesterday, today and tomorrow

Get the corresponding daily note associated with the day. If passed a `label` that label will be append it to the filename with an `_` character.

[,bash]
----
shv today school # It will edit the file 2023-01-01_school.$SHV_EXT
----

==== history

Searches through your edit history and uses your picker to select some notes.

== Customization

NOTE: The values of the variables below are the defaults.

CAUTION: All the regex used here needs to be POSIX compatible.

[,bash]
----
# Path to notes
export SHV_PATH="$HOME/Documents/notes"

# Path to diary
export SHV_DIARY_PATH="$SHV_PATH/diary"

# Picker used to select notes
export SHV_PICKER="fzf -m --ansi --print-query --bind=alt-enter:print-query"

# Extensions to search. Space separated list.
# NOTE: the first of the list will be used as your primary extention when creating a file.
export SHV_EXTS="md adoc txt org"

# Default subcommand run if calling shv without arguments (see list of subcommand above for more info).
# NOTE: subcommands that needs input will not work
export SHV_DEFAULT_CMD=search

# The editor used to edit your notes.
export SHV_EDITOR=$EDITOR

# Bookmarked files. Space separated list.
export SHV_BMS="scratchpad.md"

# String passed to 'date' command.
# For see how to modify this value check 'man date'
export SHV_DATE_FMT="%Y-%m-%d"

# Space separated list of ignored files and directories
# NOTE: if you are trying to ignore a directory put an wildchar so it matches everything under it
export SHV_IGNORE="./.obsidian/* ./.git/*"

# If you want that your editor pwd is in the SHV_PATH
export SHV_AUTO_CD=true

# If you want that shv remember's your edited note history
export SHV_HISTORY=true
----

== Philosophy

[quote,scrod creator of notational_velocity]
The reasoning behind Notational Velocity's present lack of multi-database support is that storing notes in separate databases would 1) Require the same kinds of decisions that category/folder-based organizers force upon their users (e.g., "Is this note going to be work-specific or home-specific?"), and 2) Defeat the point of instantaneous searching by requiring, ultimately, the user to repeat each search for every database in use.

+
+
By providing a default directory, we offer (one) fix to the first issue.

By searching the whole set of directories simultaneously, we handle the second.

It also handles Notational Velocity's issue with multiple databases. UNIX does not allow repeated filenames in the same folder, but often the parent folder provides context, like in `workout/TODO.md` and `coding/TODO.md`.
