#!/bin/sh

set -e

OS=$(uname)
AUTO_CD=${SHV_AUTO_CD:-"true"}
EXT=${SHV_EXT:-"md"}
DATE_FMT=${SHV_DATE_FMT:-"%Y-%m-%d"}
IGNORE=${SHV_IGNORE:-"./.obsidian/* ./.git/* ./*.pdf"}
JOURNAL_PATH=${SHV_JOURNAL_PATH:-"$SHV_PATH"}
NOTE_PATH=${SHV_PATH:-${XDG_DATA_HOME:-${HOME}/.local/share}/notes}
PICKER=${SHV_PICKER:-"fzf -m --ansi --print-query --bind=alt-enter:print-query"}
SUBCMD=${SHV_DEFAULT_CMD:-"select"}
NORMALIZE_CH=${SHV_NORMALIZE_CH:-"-"}
GREP_CMD=${SHV_GREP_CMD:-"$(type rg >/dev/null 2>/dev/null && echo 'rg -H' || echo 'grep -H')"}

###### UTILITY ######

usage() {
    cat <<EOF
$0: illegal subcommand -- $1
usage: shv [FLAGS] [SUBCOMMAND] [ARGS]

more info: 
  man shv
EOF
    exit 0
}

# Echo to stderr and quit
die() { printf '%s: %s.\n' "$0" "$1" >&2 && exit 1; }

strip() {
    str="${1#"${1%%[![:space:]]*}"}"
    str="${str%"${str##*[![:space:]]}"}"
    printf "%s\n" "$str"
}

# Normalize string in an usable state
# $1: String
normalize() {
    strip "$1" | sed "s/\n/#/g; s/\ /$NORMALIZE_CH/g; s/\n/#/g; s/#/\s/g"
}

# Parse output of fuctions and return string of files
# $1: filenames
# $2: directory
parse() {
    args=$(normalize "$1")
    for i in $args; do
        [ -f "$i" ] &&
            file="$file $i" ||
            tmp="$2/$i.$EXT"
    done
    printf "%s\n" "${file:-$tmp}"
}

# List files in dir
# $1: directory
get_files() {
        tmp="$tmp -not -path $ign"
    for ign in $IGNORE; do
    done
    eval "find $1 -type f $tmp"
}

# Returns the date of selected day by standard of date command
# $1: n of days
get_date() {
    if [ "$OS" = "Linux" ]; then
        date -d "$1 days" +"$DATE_FMT"
    else
        date -v"$1"d +"$DATE_FMT"
    fi
}

###### COMMANDS ######

# Returns the path to note of specified day
# $1: n days
# $2: label
journal_note() {
    date=$(get_date "$1")
    [ -z "$2" ] && NORMALIZE_CH=""
    printf "%s/%s$NORMALIZE_CH%s.%s\n" "$JOURNAL_PATH" "$date" "$2" "$EXT"
}

# Handler to search/create notes
search_notes() {
    sel=$(get_files "$NOTE_PATH" | xargs -I {} $GREP_CMD "" {} | $PICKER | sed "s/:.*//g")
    [ -z "$sel" ] && exit 0
    parse "$sel" "$NOTE_PATH"
}

# $1: directory to search
select_notes() {
    sel=$(get_files "$1" | $PICKER | sed "s/\n/#/g")
    [ -z "$sel" ] && exit 0
    parse "$sel" "$1"
}

###### MAIN ######

while [ $# -gt 0 ]; do
    case $1 in
    --auto-cd)
        AUTO_CD=true
        shift
        ;;
    --no-auto-cd)
        AUTO_CD=false
        shift
        ;;
    -p | --note-path)
        NOTE_PATH="$2"
        shift
        shift
        ;;
    -j | --journal-path)
        JOURNAL_PATH="$2"
        shift
        shift
        ;;
    -i | --ignore)
        IGNORE="$2"
        shift
        shift
        ;;
    -c | --normalize-ch)
        NORMALIZE_CH="$2"
        shift
        shift
        ;;
    -P | --picker)
        picker="$2"
        shift
        shift
        ;;
    -g | --grep_cmd)
        GREP_CMD="$2"
        shift
        shift
        ;;
    -e | --ext)
        EXT="$2"
        shift
        shift
        ;;
    *)
        break
        ;;
    esac
done

case ${1:-$SUBCMD} in
j | journal)
    note=$(select_notes "$JOURNAL_PATH")
    ;;
g | grep)
    note=$(search_notes)
    ;;
s | select)
    note=$(select_notes "$NOTE_PATH")
    ;;
t | today)
    note=$(journal_note +0 "$2")
    ;;
tm | tomorrow)
    note=$(journal_note +1 "$2")
    ;;
y | yesterday)
    note=$(journal_note -1 "$2")
    ;;
*)
    usage "$1"
    ;;
esac

"$AUTO_CD" && cd "$NOTE_PATH"
[ -n "$note" ] && eval "${EDITOR:-vi} $note"
